### ISSUE TITLE
Move PUID/PGID to runtime Phase

### ISSUE THREAD

**Issue by fti7** [milsimdk/ots-docker#1]
Some Vendors allow setting PUID/PGID at Runtime, so no need for the Users to rebuild the Images

Example: linuxserver.io Images (Example Repo: https://github.com/linuxserver/docker-beets/tree/master)

https://docs.linuxserver.io/general/understanding-puid-and-pgid/

compose.yml
    environment:
      - PUID=1000
      - PGID=1000

**Comment by nerdalertdk** [comment]
Hi

Yeah thought about it, but didn’t want to do it 😂
This is still WIP and mostly for me

Just wanted to share it with others so they don’t need to create the base image them self

Might get to it eventually 😅

**Comment by fti7** [comment]
> Hi
> 
> Yeah thought about it, but didn’t want to do it 😂 This is still WIP and mostly for me
> 
> Just wanted to share it with others so they don’t need to create the base image them self
> 
> Might get to it eventually 😅


Thats ok. i think the dockerized Deployment is very important. Maybe we should try to get this in the Core Project/Installer so there is more help/contributors for extending/evolving?

**Comment by nerdalertdk** [comment]
Hi

Removed a lot of the user stuff.
You can now set the user id in the `compose.override.yaml` file
